### ISSUE TITLE
Preprocessor enhancements

### ISSUE THREAD

**Issue by jacojoubert** [prototypal-io/untitled-ui#95]
### Animations

When we create keyframes we currently do 

``` css
.some-rule {
  animation: ui-input--default--error-highlight 0.2s 1;
}

@at-root {
    /* Focus Glow */
    @keyframes ui-input--default--focus-highlight {
      ...
    }
}
```

This hard codes the animation name and property value. This doesn't allow us to customize the value of an animation when creating scss only kinds. We need a way to write the component name into keyframe names and animation properties.
### Contextual components

When creating a theme the child components don't get prepended with the theme name. For example, in the `tomato` theme creating a new `ui-tooltip--default.scss` file and registering it still outputs the following html:

``` html
<div class="tomato--ui-tooltip--default ui-font-size--medium ">
  <span class="ui-tooltip--default-target">
    <div class="form-name--tooltip--target">?</div>
  </span>
</div>
```

I would expect `ui-tooltip--default-target` to instead be `tomato--ui-tooltip--default-target`.
### ~~Ember helper classes~~

We currently use Ember helpers like `input` and `textarea` and assign them classes:

``` hbs
{{input class=(concat "ui-input--default--input "
                      (ui-state states 'disabled' 'error' el='ui-input--default--input'))}}
```

This hard-codes the component name into the template and does not get rewritten. This prevents us from styling the component when creating scss only kinds.
